### ISSUE TITLE
can't work when using multi screen

### ISSUE THREAD

**Issue by zhangjie93** [ianzhao05/textshot#17]
I use two monitors , this program can't work

**Comment by ianzhao05** [comment]
Thank you for bringing this up. Can you elaborate? What exactly happens? What operating system are you on?

**Comment by zhangjie93** [comment]
the system is windows. when use two monitors, the program only works on the screen where the cursor  is and I can't screenshot on the other screen

**Comment by ianzhao05** [comment]
Yes, at the moment, this is intentional. The way to use it is to move the cursor to the screen you want to screenshot and then run the script. You can capture text on any monitor this way. Implementing a feature that would create a overlay on all monitors (like built-in screenshot tools) is something that I will work on in the near future. I will notify you when this is finished.
