### ISSUE TITLE
macOS Big Sur opens new screen

### ISSUE THREAD

**Issue by DavBebawy** [ianzhao05/textshot#30]
I just downloaded text shot on my Mac and installed all the dependencies but have been experiencing this weird behavior where as soon as I run it it will open a new screen to the right with no open apps and would only allow me to screenshot there. Did anyone else encounter this or have a fix?

```2021-02-27 19:08:54.739 Python[952:13732] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/ld/wjmpqdpj1pq2j4j_svh1j8740000gn/T/org.python.python.savedState```

![Screen Recording](https://user-images.githubusercontent.com/52139648/109404006-d17d3680-792f-11eb-9907-11f9430dea10.gif)

**Comment by ianzhao05** [comment]
Hi, thanks for raising this issue. It is likely caused by a lack of permissions to capture the screen. You can fix this by going to System Preferences > Security & Privacy > Privacy > Screen Recording, then checking the box for Terminal/iTerm. If this fixes the issue, I would be happy to add a note to the README for future users.

The message that you are getting does not affect functionality, but [this StackOverflow question](https://stackoverflow.com/q/18733965) has some potential fixes.

**Comment by DavBebawy** [comment]
Thanks for the quick reply. I suspected it was permissions related but was not sure how to give textshot permission, allowing the terminal makes sense. Allowing iTerm fixed this problem, but now it's unable to read text from image. I have all the requirements downloaded, not sure what's wrong this time.

```INFO: Unable to read text from image, did not copy```

![Screen Recording](https://user-images.githubusercontent.com/52139648/109429327-389af980-79c9-11eb-8d6e-4abf861f51ba.gif)

**Comment by ianzhao05** [comment]
It works fine on that given text for me. Does it work on some basic text? Like a few words with black letters on a white background? Regardless, you can try two things:

- adding `pil_img.show()` after line 84 in `textshot.py` as debugging to see if the correct portion of the screen is being captured
- increasing the `timeout` by editing line 88 in `textshot.py` to give more time for the OCR software to recognize the text (I doubt that this is the problem unless your computer is extremely old)

It is to be expected that it does not work on all images of text given that OCR is rather fragile if it is not fine-tuned to work on specific types of images. TextShot does not do any of this fine-tuning in order to cater to all types of images.

**Comment by hasantahir** [comment]
I was having the same issue. Although not making sense, but a clean install fixed it for me.

**Comment by ianzhao05** [comment]
Closing because the original issue has been solved and inactivity, also added note to README
